language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0snapshot'
    - nightly
jobs:
    allow_failures:
        - php: nightly
install: composer install
script: ./vendor/bin/phpunit tests
