language: php
dist: focal
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0'
    - '8.1'
    - nightly
jobs:
    allow_failures:
        - php: nightly
    include:
        - php: 7.1
        dist: xenial
        - php: 7.2
        dist: xenial
        - php: 7.3
        dist: xenial
        - php: 7.4
        dist: focal
        - php: 8.0
        dist: focal
        - php: 8.1
        dist: focal
        - php: 8.2
        dist: focal
        - php: nightly
        dist: jammy
install: composer install
script: ./vendor/bin/phpunit tests
